name: Production Build

on:
  pull_request_target:
    branches:
      - main
permissions:
  pull-requests: write
  contents: write
  statuses: write
  actions: write
  checks: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: pytest -q
      - name: Run smoke checks
        run: python app.py --run-checks

  merge:
    needs: test
    if: ${{ !github.event.pull_request.draft && github.event.pull_request.head.repo.fork == false }}
    runs-on: ubuntu-latest
    steps:
      - name: Merge the PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ github.token }}
          script: |
            const { owner, repo } = context.repo;
            const pr = (await github.paginate(github.rest.pulls.list, { owner, repo, state: 'open' }))
              .find(p => p.head.sha === context.payload.workflow_run.head_sha);
            if (!pr) core.setFailed('No matching PR for successful run'), process.exit(1);
            await github.rest.pulls.merge({ owner, repo, pull_number: pr.number, merge_method: 'squash' });
